#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-ifaddr
Version  : 0.2.0
Release  : 37
URL      : https://files.pythonhosted.org/packages/e8/ac/fb4c578f4a3256561548cd825646680edcadb9440f3f68add95ade1eb791/ifaddr-0.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e8/ac/fb4c578f4a3256561548cd825646680edcadb9440f3f68add95ade1eb791/ifaddr-0.2.0.tar.gz
Summary  : Cross-platform network interface and IP address enumeration library
Group    : Development/Tools
License  : MIT
Requires: pypi-ifaddr-license = %{version}-%{release}
Requires: pypi-ifaddr-python = %{version}-%{release}
Requires: pypi-ifaddr-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
ifaddr - Enumerate network interfaces/adapters and their IP addresses
=====================================================================

%package license
Summary: license components for the pypi-ifaddr package.
Group: Default

%description license
license components for the pypi-ifaddr package.


%package python
Summary: python components for the pypi-ifaddr package.
Group: Default
Requires: pypi-ifaddr-python3 = %{version}-%{release}

%description python
python components for the pypi-ifaddr package.


%package python3
Summary: python3 components for the pypi-ifaddr package.
Group: Default
Requires: python3-core
Provides: pypi(ifaddr)

%description python3
python3 components for the pypi-ifaddr package.


%prep
%setup -q -n ifaddr-0.2.0
cd %{_builddir}/ifaddr-0.2.0
pushd ..
cp -a ifaddr-0.2.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656400568
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-ifaddr
cp %{_builddir}/ifaddr-0.2.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-ifaddr/dbd6aca799aa635e17e93c8807f54f6aeeddb025
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-ifaddr/dbd6aca799aa635e17e93c8807f54f6aeeddb025

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
